language: php

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

addons:
    code_climate:
        repo_token: f85424364bfe37962e05e7a1a8c7781cc214b28786ed416b6c9128176713e774

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --prefer-source --no-interaction

before_script:
  - mysql -u root -e 'set global innodb_large_prefix=1;'
  - mysql -u root -e 'set global innodb_file_format="Barracuda";'
  - mysql -u root -e 'set global innodb_file_format_max="Barracuda";'
  - mysql -u root -e 'set global innodb_file_per_table=true;'
  - mysql -e 'create database friendships_test;'
  - cd -

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
